export type SiteLanguage = 'ko' | 'mn'

const messages = {
  ko: {
    'language.select': '언어 선택',
    'language.ko': '한국어',
    'language.mn': '몽골어',
    'church.name': '생명수 교회',
    'church.region': '날라흐',
    'church.fullName': '날라흐 생명수 교회',
    'nav.home': '홈',
    'nav.sermons': '이번주 말씀',
    'nav.notices': '공지사항',
    'nav.qt': 'QT 묵상',
    'nav.events': '성경 통독',
    'nav.teachers': '선생님방',
    'nav.admin': '관리자',
    'sidebar.expand': '사이드바 펼치기',
    'sidebar.collapse': '사이드바 접기',
    'auth.logout': '로그아웃',
    'role.master': '마스터',
    'role.teacher': '교사',
    'role.normal': '성도',
    'home.dailyWord': '오늘의 말씀',
    'home.verseMain': '“내가 주는 물을 마시는 자는 영원히 목마르지 아니하리니\n내가 주는 물은 그 속에서 영생하도록 솟아나는 샘물이 되리라.”',
    'home.verseSecondary': 'Харин миний өгөх усаас уух хүн хэзээ ч цангахгүй.\nХарин миний өгөх ус тэр хүний дотор мөнх амьдрал уруу оргилох булгийн ус болно.',
    'home.verseRef': '요한복음 4:14 · Иохан 4:14',
    'home.shortcut.sermonsTitle': '이번주 말씀',
    'home.shortcut.sermonsDesc': '주일 강단 설교 아카이브',
    'home.shortcut.noticesTitle': '공지사항',
    'home.shortcut.noticesDesc': '교회 주요 소식 및 안내',
    'home.shortcut.qtTitle': 'QT 묵상 나눔',
    'home.shortcut.qtDesc': '오늘의 말씀 묵상 & 나눔',
    'home.shortcut.eventsTitle': '성경 통독 릴레이',
    'home.shortcut.eventsDesc': '온 교회 함께하는 통독 레이스',
    'home.recentSermon': '최근 설교',
    'home.sermonTitle': '생수의 강이 흐르는 삶',
    'home.sermonPassage': '요한복음 7:37~39',
    'home.sermonDate': '2024. 05. 19 · 주일 예배',
    'home.watchSermon': '설교 다시보기',
    'home.churchNews': '교회 소식',
    'home.news.retreat': '몽고동부 여름 수련회 안내',
    'home.news.bazaar': '선교 바자회 안내',
    'home.news.welcome': '새가족 환영 모임',
    'home.more': '더보기 →',
    'home.worshipGuide': '예배 안내',
    'home.worship.sunday': '주일 예배',
    'home.worship.sundayTime': '주일 오전 11:00',
    'home.worship.wednesday': '수요 예배',
    'home.worship.wednesdayTime': '수요일 오후 7:30',
    'home.worship.dawn': '새벽 기도회',
    'home.worship.dawnTime': '월 ~ 금 오전 6:00',
    'home.allSchedule': '전체 일정 보기 →',
    'common.cancel': '작성 취소',
    'common.delete': '삭제',
    'common.viewDetail': '자세히 보기',
    'sermons.title': '이번주 말씀',
    'sermons.subtitle': '주일 강단에서 선포된 하나님의 말씀을 기록하고 공유합니다.',
    'sermons.create': '새 말씀 등록',
    'sermons.empty': '등록된 말씀이 없습니다.',
    'notices.title': '공지사항',
    'notices.subtitle': '교회 소식, 주간 광고 및 긴급 공지를 확인하실 수 있습니다.',
    'notices.create': '공지 작성',
    'notices.pinned': '중요 공지',
    'notices.empty': '등록된 공지사항이 없습니다.',
    'qt.title': '매일 QT 묵상 나눔',
    'qt.subtitle': '오늘 주신 말씀을 깊이 묵상하고 성도의 은혜를 댓글로 나눕니다.',
    'qt.dailyWord': '오늘의 말씀',
    'qt.empty': '선택하신 날짜의 묵상 말씀이 아직 등록되지 않았습니다.',
    'qt.emptySub': '관리자분들께서 매일 아침 업데이트를 준비 중입니다.',
    'qt.loading': '묵상 말씀을 불러오는 중...',
    'qt.comments': '은혜 나눔 묵상 댓글',
    'qt.commentPlaceholder': '성령님께서 오늘 주신 은혜와 깨달음을 성도들과 나누어 보세요.',
    'qt.commentSubmit': '묵상 등록',
    'qt.noComments': '첫 묵상 나눔을 작성하여 은혜를 나누어 보세요.',
    'events.title': '성경 통독 릴레이',
    'events.subtitle': '온 교회가 한 마음으로 하나님의 말씀을 처음부터 끝까지 함께 통독해 나갑니다.',
    'events.total': '교회 전체 통독 장수',
    'events.progress': '통독 달성률',
    'events.participants': '참여 성도 수',
    'events.chapters': '장',
    'events.people': '명',
    'events.start': '시작 (창세기)',
    'events.goal': '목표 달성 (신구약 1,189장 완독)',
    'events.report': '성경 읽기 인증하기',
    'events.feed': '실시간 통독 피드',
    'events.noLogs': '아직 통독 기록이 없습니다. 첫 번째 주인공이 되어 보세요!',
  },
  mn: {
    'language.select': 'Хэл сонгох',
    'language.ko': 'Солонгос хэл',
    'language.mn': 'Монгол хэл',
    'church.name': 'Амийн Усны Гол Чуулган',
    'church.region': 'Налайх',
    'church.fullName': 'Налайх Амийн Усны Гол Чуулган',
    'nav.home': 'Нүүр',
    'nav.sermons': 'Энэ долоо хоногийн номлол',
    'nav.notices': 'Зарлал',
    'nav.qt': 'QT бясалгал',
    'nav.events': 'Библи уншлага',
    'nav.teachers': 'Багш нарын өрөө',
    'nav.admin': 'Удирдлага',
    'sidebar.expand': 'Хажуугийн цэсийг нээх',
    'sidebar.collapse': 'Хажуугийн цэсийг хаах',
    'auth.logout': 'Гарах',
    'role.master': 'Админ',
    'role.teacher': 'Багш',
    'role.normal': 'Итгэгч',
    'home.dailyWord': 'Өнөөдрийн эшлэл',
    'home.verseMain': '“Харин Миний өгөх уснаас уух хүн хэзээ ч цангахгүй.\nМиний өгөх ус түүнд мөнх амь өөд оргилох булгийн ус болно.”',
    'home.verseSecondary': '내가 주는 물을 마시는 자는 영원히 목마르지 아니하리니\n내가 주는 물은 그 속에서 영생하도록 솟아나는 샘물이 되리라.',
    'home.verseRef': 'Иохан 4:14 · 요한복음 4:14',
    'home.shortcut.sermonsTitle': 'Энэ долоо хоногийн номлол',
    'home.shortcut.sermonsDesc': 'Ням гарагийн номлолын архив',
    'home.shortcut.noticesTitle': 'Зарлал',
    'home.shortcut.noticesDesc': 'Чуулганы мэдээ, мэдээлэл',
    'home.shortcut.qtTitle': 'QT бясалгал хуваалцах',
    'home.shortcut.qtDesc': 'Өнөөдрийн үгийг хамтдаа бясалгах',
    'home.shortcut.eventsTitle': 'Библи унших буухиа',
    'home.shortcut.eventsDesc': 'Чуулгаараа хамт Библи унших',
    'home.recentSermon': 'Сүүлийн номлол',
    'home.sermonTitle': 'Амийн усны гол урсах амьдрал',
    'home.sermonPassage': 'Иохан 7:37–39',
    'home.sermonDate': '2024. 05. 19 · Ням гарагийн мөргөл',
    'home.watchSermon': 'Номлол дахин үзэх',
    'home.churchNews': 'Чуулганы мэдээ',
    'home.news.retreat': 'Дорнод Монголын зуны цугларалт',
    'home.news.bazaar': 'Миссионерийн сайн үйлсийн худалдаа',
    'home.news.welcome': 'Шинэ гэр бүлийг угтах уулзалт',
    'home.more': 'Дэлгэрэнгүй →',
    'home.worshipGuide': 'Мөргөлийн хуваарь',
    'home.worship.sunday': 'Ням гарагийн мөргөл',
    'home.worship.sundayTime': 'Ням 11:00',
    'home.worship.wednesday': 'Лхагва гарагийн мөргөл',
    'home.worship.wednesdayTime': 'Лхагва 19:30',
    'home.worship.dawn': 'Өглөөний залбирал',
    'home.worship.dawnTime': 'Даваа–Баасан 06:00',
    'home.allSchedule': 'Бүх хуваарийг харах →',
    'common.cancel': 'Болих',
    'common.delete': 'Устгах',
    'common.viewDetail': 'Дэлгэрэнгүй',
    'sermons.title': 'Энэ долоо хоногийн номлол',
    'sermons.subtitle': 'Ням гарагийн индэр дээр тунхаглагдсан Бурханы үгийг тэмдэглэн хуваалцана.',
    'sermons.create': 'Шинэ номлол бүртгэх',
    'sermons.empty': 'Бүртгэгдсэн номлол алга байна.',
    'notices.title': 'Зарлал',
    'notices.subtitle': 'Чуулганы мэдээ, долоо хоногийн зарлал болон яаралтай мэдээллийг үзнэ үү.',
    'notices.create': 'Зарлал бичих',
    'notices.pinned': 'Чухал зарлал',
    'notices.empty': 'Бүртгэгдсэн зарлал алга байна.',
    'qt.title': 'Өдөр тутмын QT бясалгал',
    'qt.subtitle': 'Өнөөдрийн үгийг гүн бясалгаж, хүлээн авсан ивээлээ хамтдаа хуваалцана.',
    'qt.dailyWord': 'Өнөөдрийн эшлэл',
    'qt.empty': 'Сонгосон өдрийн бясалгал хараахан бүртгэгдээгүй байна.',
    'qt.emptySub': 'Өдөр тутмын шинэчлэл удахгүй нэмэгдэх болно.',
    'qt.loading': 'Бясалгалын үгийг ачаалж байна...',
    'qt.comments': 'Ивээл хуваалцах сэтгэгдэл',
    'qt.commentPlaceholder': 'Өнөөдөр Ариун Сүнснээс авсан ивээл, ухаарлаа хуваалцаарай.',
    'qt.commentSubmit': 'Бясалгал нэмэх',
    'qt.noComments': 'Анхны бясалгалаа бичиж, ивээлээ хуваалцаарай.',
    'events.title': 'Библи унших буухиа',
    'events.subtitle': 'Чуулгаараа нэг сэтгэлээр Бурханы үгийг эхнээс нь дуустал хамтдаа уншина.',
    'events.total': 'Чуулганы нийт уншсан бүлэг',
    'events.progress': 'Уншлагын гүйцэтгэл',
    'events.participants': 'Оролцсон итгэгчид',
    'events.chapters': 'бүлэг',
    'events.people': 'хүн',
    'events.start': 'Эхлэл (Эхлэл ном)',
    'events.goal': 'Зорилго (Хуучин, Шинэ гэрээний 1,189 бүлэг)',
    'events.report': 'Библи уншсанаа бүртгэх',
    'events.feed': 'Уншлагын шууд мэдээ',
    'events.noLogs': 'Уншлагын бүртгэл алга байна. Анхны оролцогч болоорой!',
  },
} as const

type TranslationKey = keyof typeof messages.ko

export const useLanguage = () => {
  const language = useCookie<SiteLanguage>('site-language', {
    default: () => 'ko',
    sameSite: 'lax',
  })

  const t = (key: TranslationKey) => messages[language.value]?.[key] ?? messages.ko[key]

  const setLanguage = (value: SiteLanguage) => {
    language.value = value
  }

  if (import.meta.client) {
    watch(language, (value) => {
      document.documentElement.lang = value
    }, { immediate: true })
  }

  return { language, setLanguage, t }
}
